installed:
  - riCore
  - riSimplex
  - riCache
  - riCjLoader
  - riPlugin
  - riUtility
  - riLog
  - riSession
  - riResultList
  - riZCAdmin
  
activated:
  #- riCore
  - riSimplex
  - riCache
  - riCjLoader  
  - riPlugin
  - riUtility
  - riLog
  - riSession
  - riResultList
  - riZCAdmin

backend:
    preload: [riCore, riCache, riUtility, riLog, riSession, riResultList, riZCAdmin, riCjLoader]

frontend:
    preload: [riCore, riCache, riUtility, riLog, riSession, riResultList, riCjLoader]

# templating
templating: { engines: ['php'] }    