# the settings from here should not be edited or overwritten
routes:
  admin_plugins:
    pattern:  /manager/
    defaults: { _controller: plugins\riCore\AdminController::indexAction }
  admin_plugins_info:
    pattern:  /info/
    defaults: { _controller: plugins\riCore\AdminController::infoAction }
  admin_plugins_install:
    pattern:  /install/
    defaults: { _controller: plugins\riCore\AdminController::installAction }
  admin_plugins_uninstall:
    pattern:  /uninstall/
    defaults: { _controller: plugins\riCore\AdminController::uninstallAction }
  admin_plugins_activate:
    pattern:  /activate/
    defaults: { _controller: plugins\riCore\AdminController::activateAction }
  admin_plugins_deactivate:
    pattern:  /deactivate/
    defaults: { _controller: plugins\riCore\AdminController::deactivateAction }
  admin_plugins_reset_settings:
    pattern:  /reset_settings/
    defaults: { _controller: plugins\riCore\AdminController::resetSettingsAction }
  admin_plugins_load_theme_settings:
    pattern:  /load_theme_settings/
    defaults: { _controller: plugins\riCore\AdminController::loadThemeSettingsAction }

global:    
  backend:
    menu:
      extras:
        - {text: Plugins Manager, link: ri.php/ricore/manager/}