# the settings from here should not be edited or overwritten
routes:
  admin_manager:
    pattern:  /manager/
    defaults: { _controller: plugins\riCore\AdminController::indexAction }
  admin_plugins_info:
    pattern:  /plugins_info/
    defaults: { _controller: plugins\riCore\AdminController::pluginsInfoAction }
  admin_plugins_install:
    pattern:  /plugins_install/
    defaults: { _controller: plugins\riCore\AdminController::pluginsInstallAction }
  admin_plugins_uninstall:
    pattern:  /plugins_uninstall/
    defaults: { _controller: plugins\riCore\AdminController::pluginsUninstallAction }
  admin_plugins_activate:
    pattern:  /plugins_activate/
    defaults: { _controller: plugins\riCore\AdminController::pluginsActivateAction }
  admin_plugins_deactivate:
    pattern:  /plugins_deactivate/
    defaults: { _controller: plugins\riCore\AdminController::pluginsDeactivateAction }
  admin_plugins_reset_settings:
    pattern:  /reset_settings/
    defaults: { _controller: plugins\riCore\AdminController::resetSettingsAction }
  admin_plugins_load_theme_settings:
    pattern:  /load_theme_settings/
    defaults: { _controller: plugins\riCore\AdminController::loadThemeSettingsAction }

global:    
  backend:
    menu:
      extras:
        - {text: Plugins Manager, link: ri.php/ricore/manager/}